name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Fix docker socket permissions (if needed)
        run: |
          sudo chmod 666 /var/run/docker.sock || true
#          sudo usermod -aG docker $USER || true

      - name: Docker smoke test (required by Testcontainers)
        run: |
          docker version
          docker info
          ls -lah /var/run/docker.sock || true
          docker ps
          docker run --rm hello-world
          

      - name: Build & Test
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew clean build

      - name: Print Testcontainers error from test report
        if: failure()
        run: |
          grep -Rni "DockerClientProviderStrategy|Could not find a valid Docker environment|Ryuk|docker.sock|IllegalStateException" build/reports/tests/test || true
          f="build/reports/tests/test/classes/com.song.my_pim.it.ExportArticleControllerIT.html"
          test -f "$f" && sed -n '1,160p' "$f" || true

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: my-pim-jar
          path: build/libs/*.jar
