name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

#    services:
#      postgres:
#        image: postgres:16
#        env:
#          POSTGRES_DB: devdb
#          POSTGRES_USER: user
#          POSTGRES_PASSWORD: user
#        ports:
#          - 5432:5432
#        options: >-
#          --health-cmd="pg_isready -U user -d devdb"
#          --health-interval=5s
#          --health-timeout=5s
#          --health-retries=20
          

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker || true
          docker version
          docker info

      - name: Diagnose Docker for Testcontainers
        run: |
          whoami
          uname -a
          ls -lah /var/run || true
          ls -lah /var/run/docker.sock || true
          docker version || true
          docker info || true
          docker ps || true

      - name: Build & Test
        env:
          SPRING_PROFILES_ACTIVE: test
#          DOCKER_HOST: unix:///var/run/docker.sock
#          TESTCONTAINERS_HOST_OVERRIDE: localhost
#          TESTCONTAINERS_RYUK_DISABLED: "true"
        run: ./gradlew clean build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: my-pim-jar
          path: build/libs/*.jar
